//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Psychological_diagnosis_system
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class pdsEntities : DbContext
    {
        public pdsEntities()
            : base("name=pdsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<record> record { get; set; }
        public virtual DbSet<sas_answer_card> sas_answer_card { get; set; }
        public virtual DbSet<sds_answer_card> sds_answer_card { get; set; }
        public virtual DbSet<self_rating_anxiety_scale> self_rating_anxiety_scale { get; set; }
        public virtual DbSet<self_rating_depression_scale> self_rating_depression_scale { get; set; }
        public virtual DbSet<university_personality_inventory> university_personality_inventory { get; set; }
        public virtual DbSet<upi_answer_card> upi_answer_card { get; set; }
        public virtual DbSet<user_info> user_info { get; set; }
        public virtual DbSet<user_test> user_test { get; set; }
    }
}
