//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Psychological_diagnosis_system
{
    using System;
    using System.Collections.Generic;
    
    public partial class record
    {
        public string GUID { get; set; }
        public string ID { get; set; }
        public string USER_ID { get; set; }
        public string TEST_NAME { get; set; }
        public System.DateTime DATE { get; set; }
        public System.TimeSpan TIME { get; set; }
    }
}
