//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Psychological_diagnosis_system
{
    using System;
    using System.Collections.Generic;
    
    public partial class sas_answer_card
    {
        public string GUID { get; set; }
        public string RECORD_ID { get; set; }
        public int QUES_NUM { get; set; }
        public string SELECT { get; set; }
        public string TENDENCY { get; set; }
        public int WEIGHT { get; set; }
    }
}
