//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Psychological_diagnosis_system
{
    using System;
    using System.Collections.Generic;
    
    public partial class scl90_scale
    {
        public int ID { get; set; }
        public int SELECT_NUM { get; set; }
        public string CONTENT { get; set; }
        public string TENDENCY { get; set; }
        public string SELECT_A_CONTENT { get; set; }
        public string SELECT_B_CONTENT { get; set; }
        public string SELECT_C_CONTENT { get; set; }
        public string SELECT_D_CONTENT { get; set; }
        public string SELECT_E_CONTENT { get; set; }
        public int A_WEIGHT { get; set; }
        public int B_WEIGHT { get; set; }
        public int C_WEIGHT { get; set; }
        public int D_WEIGHT { get; set; }
        public int E_WEIGHT { get; set; }
    }
}
