//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Psychological_diagnosis_system
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_info
    {
        public string USER_GUID { get; set; }
        public string ID { get; set; }
        public string NAME { get; set; }
        public System.DateTime INPUT_DATE { get; set; }
        public string PROVINCE { get; set; }
        public string CITY { get; set; }
        public string DISTRICT_TOWN { get; set; }
        public string DETAIL_ADDRESS { get; set; }
        public string ID_NUMBER { get; set; }
        public string SEX { get; set; }
        public string MARRIAGE { get; set; }
        public int AGE { get; set; }
        public string EDUCATION { get; set; }
        public string CAREER { get; set; }
    }
}
